# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Profile Metrics
on:
  schedule: [{cron: "*/5 * * * *"}]
  #workflow_dispatch:
  #push: {branches: ["master", "main", "development", "release/*"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
      - uses: actions/setup-node@v1
        with:
          read: user
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          repositories_forks: yes
          repositories_affiliations: yes
          plugin_habits: yes
          plugin_followup: yes
          plugin_traffic: yes

          # Options
          user: mwebber3
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Detroit
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 100
          plugin_stars: yes
          plugin_stars_limit: 4
